#
# ~/.bashrc
#
eval "$(starship init bash)"
# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
alias grep='grep --color=auto'
PS1='[\u@\h \W]\$ '

alias update='sudo pacman -Syu && sudo pacman -Sy && yay && flatpak update'
alias cleanshot='rm -rf ~/screenshot/output/* && rm -rf ~/screenshot/region/* && rm -rf ~/screenshot/window/*'
alias nvidia='sudo mkinitcpio -P'
alias resetwaybar='killall waybar && hyprctl dispatch exec waybar'
alias disco='pkexec env WAYLAND_DISPLAY=$WAYLAND_DISPLAY XDG_RUNTIME_DIR=$XDG_RUNTIME_DIR gparted'
alias cleandownload='rm -rf ~/ssd/download/* && rm -rf ~/Downloads/*'
alias z="cd"

fastfetch
