###   ROLES     ###

#lanche
$terminal = kitty
$fileManager = nemo
$browser = helium-browser
$menu = rofi -show drun
$wall = ~/.config/hypr/script/rofi-wallpaper.sh

#print
$print = hyprshot -m output -o ~/screenshot/output/
$printwindow = hyprshot -m window -o ~/screenshot/window/
$printregion = hyprshot -m region -o ~/screenshot/region/

# rmpc / mpd music controls
$pause = mpc toggle
$next_song = mpc next
$previous_song = mpc prev
$less_volume = mpc volume -5
$more_volume = mpc volume +5

###   AUTO START     ###

exec-once = awww-daemon
exec-once = waybar
exec-once = dunst
exec-once = helium-browser
exec-once = vesktop
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

exec-once = [workspace special:magic silent] kitty --class rmpc -e rmpc

### Open apps in special workspace ###
windowrule = match:class rmpc, workspace special:magic silent
windowrule = match:class vesktop, workspace special:magic silent
windowrule = match:class Vesktop, workspace special:magic silent

###   SOURCES     ###

source = ./binds.conf
source = ./lookandfeel.conf
source = ./monitors.conf
