### HYPRLOCK ###

general {
    hide_cursor = true
    disable_loading_bar = true
    immediate_render = true
}

background {
    monitor =
    path = screenshot

    blur_passes = 3
    blur_size = 7

    noise = 0.018
    contrast = 0.88
    brightness = 0.48
    vibrancy = 0.08
    vibrancy_darkness = 0.28
}

# Small brand/title
label {
    monitor =
    text = HyprFlo
    color = rgba(c8bfaeff)
    font_size = 20
    font_family = JetBrainsMono Nerd Font

    position = 0, 150
    halign = center
    valign = center
}

# Clock
label {
    monitor =
    text = cmd[update:1000] date +"%H:%M"
    color = rgba(d8d3caff)
    font_size = 78
    font_family = JetBrainsMono Nerd Font

    position = 0, 72
    halign = center
    valign = center
}

# Date
label {
    monitor =
    text = cmd[update:60000] date +"%A, %d %B"
    color = rgba(b9b2a8dd)
    font_size = 16
    font_family = JetBrainsMono Nerd Font

    position = 0, 15
    halign = center
    valign = center
}

# Calm status text
label {
    monitor =
    text = locked workspace
    color = rgba(7e7870cc)
    font_size = 13
    font_family = JetBrainsMono Nerd Font

    position = 0, -25
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 310, 48
    outline_thickness = 1

    dots_size = 0.23
    dots_spacing = 0.25
    dots_center = true

    outer_color = rgba(c8bfae88)
    inner_color = rgba(18191acc)
    font_color = rgba(d8d3caff)

    fade_on_empty = false
    placeholder_text = <span foreground="##7e7870">enter password</span>

    check_color = rgba(d1b98cff)
    fail_color = rgba(c38b88ff)
    capslock_color = rgba(d1b98cff)

    fail_text = <span foreground="##c38b88">wrong password</span>

    position = 0, -82
    halign = center
    valign = center
}
